c = @(t) (exp(1j*2*pi*5*t));
x1 = @(t) (c(t) .* p1(t));
x2 = @(t) (c(t) .* p2(t));
x3 = @(t) (c(t) .* p3(t));

dtftify(p1(t), p1(n), x1(t), x1(n), ...
    '$$x_{1}(t) = p_{1}(t)\times e^{j2\pi f_{c}t}$$', ...
    '$$\hat{X}_{1}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{1}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$',...
    '$$\hat{X}_{1}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{1}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$');

dtftify(p2(t), p2(n), x2(t), x2(n), ...
    '$$x_{2}(t) = p_{2}(t)\times e^{j2\pi f_{c}t}$$', ...
    '$$\hat{X}_{2}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{2}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$',...
    '$$\hat{X}_{2}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{2}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$');

dtftify(p3(t), p3(n), x3(t), x3(n), ...
    '$$x_{3}(t) = p_{3}(t)\times e^{j2\pi f_{c}t}$$', ...
    '$$\hat{X}_{3}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{3}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$',...
    '$$\hat{X}_{3}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{3}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$');

