dtftify(p1(t), p1(n), ...
    '$$p_{s_{1}}(t) = p_{1}(t)\times\sum_{n=-N}^{N}{\delta(t-n\Delta t)}$$', ...
    '$$\hat{P}_{1}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{1}(n\Delta t)e^{j2\pi(n\Delta t)f}})$$',...
    '$$\hat{P}_{1}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{1}(n\Delta t)e^{j2\pi(n\Delta t)f}})$$');
dtftify(p2(t), p2(n), ...
    '$$p_{s_{2}}(t) = p_{2}(t)\times\sum_{n=-N}^{N}{\delta(t-n\Delta t)}$$', ...
    '$$\hat{P}_{2}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{2}(n\Delta t)e^{j2\pi(n\Delta t)f}})$$',...
    '$$\hat{P}_{2}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{2}(n\Delta t)e^{j2\pi(n\Delta t)f}})$$');
dtftify(p3(t), p3(n), ...
    '$$p_{s_{3}}(t) = p_{3}(t)\times\sum_{n=-N}^{N}{\delta(t-n\Delta t)}$$', ...
    '$$\hat{P}_{3}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{3}(n\Delta t)e^{j2\pi(n\Delta t)f}})$$',...
    '$$\hat{P}_{3}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{3}(n\Delta t)e^{j2\pi(n\Delta t)f}})$$');
