m = @(t) (cos(2*pi*f_c*t));
w1 = @(t) (m(t) .* p1(t));
w2 = @(t) (m(t) .* p2(t));
w3 = @(t) (m(t) .* p3(t));

dtftify(p1(t), p1(n), w1(t), w1(n), ...
    '$$w_{1}(t) = p_{1}(t)\times cos(2\pi f_{c}t)$$', ...
    '$$\hat{W}_{1}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{1}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$',...
    '$$\hat{W}_{1}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{1}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$');

dtftify(p2(t), p2(n), w2(t), w2(n), ...
    '$$w_{2}(t) = p_{2}(t)\times cos(2\pi f_{c}t)$$', ...
    '$$\hat{W}_{2}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{2}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$',...
    '$$\hat{W}_{2}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{2}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$');

dtftify(p3(t), p3(n), w3(t), w3(n), ...
    '$$w_{3}(t) = p_{3}(t)\times cos(2\pi f_{c}t)$$', ...
    '$$\hat{W}_{3}(f) = abs(\Delta t\sum_{n=-N}^{N}{p_{3}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$',...
    '$$\hat{W}_{3}(f) = angle(\Delta t\sum_{n=-N}^{N}{p_{3}(n\Delta t)e^{j2\pi(n\Delta t)(f-f_{c})}})$$');

